//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace client.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback registerOperationCompleted;
        
        private System.Threading.SendOrPostCallback isvalidOperationCompleted;
        
        private System.Threading.SendOrPostCallback forget_passwordOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdminisvalidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddfoodOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_foodOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViewMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkbillbydateOperationCompleted;
        
        private System.Threading.SendOrPostCallback claculate_billOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkOperationCompleted;
        
        private System.Threading.SendOrPostCallback check_statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddfineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::client.Properties.Settings.Default.client_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event registerCompletedEventHandler registerCompleted;
        
        /// <remarks/>
        public event isvalidCompletedEventHandler isvalidCompleted;
        
        /// <remarks/>
        public event forget_passwordCompletedEventHandler forget_passwordCompleted;
        
        /// <remarks/>
        public event AdminisvalidCompletedEventHandler AdminisvalidCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event AddfoodCompletedEventHandler AddfoodCompleted;
        
        /// <remarks/>
        public event Update_foodCompletedEventHandler Update_foodCompleted;
        
        /// <remarks/>
        public event ViewMenuCompletedEventHandler ViewMenuCompleted;
        
        /// <remarks/>
        public event UpdateStatusCompletedEventHandler UpdateStatusCompleted;
        
        /// <remarks/>
        public event submitCompletedEventHandler submitCompleted;
        
        /// <remarks/>
        public event checkbillbydateCompletedEventHandler checkbillbydateCompleted;
        
        /// <remarks/>
        public event claculate_billCompletedEventHandler claculate_billCompleted;
        
        /// <remarks/>
        public event checkCompletedEventHandler checkCompleted;
        
        /// <remarks/>
        public event check_statusCompletedEventHandler check_statusCompleted;
        
        /// <remarks/>
        public event AddfineCompletedEventHandler AddfineCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/register", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void register([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string q, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ans) {
            this.Invoke("register", new object[] {
                        fname,
                        lname,
                        reg,
                        password,
                        q,
                        ans});
        }
        
        /// <remarks/>
        public void registerAsync(string fname, string lname, string reg, string password, string q, string ans) {
            this.registerAsync(fname, lname, reg, password, q, ans, null);
        }
        
        /// <remarks/>
        public void registerAsync(string fname, string lname, string reg, string password, string q, string ans, object userState) {
            if ((this.registerOperationCompleted == null)) {
                this.registerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterOperationCompleted);
            }
            this.InvokeAsync("register", new object[] {
                        fname,
                        lname,
                        reg,
                        password,
                        q,
                        ans}, this.registerOperationCompleted, userState);
        }
        
        private void OnregisterOperationCompleted(object arg) {
            if ((this.registerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isvalid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isvalid([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isvalidResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isvalidResultSpecified) {
            object[] results = this.Invoke("isvalid", new object[] {
                        fname,
                        lname,
                        reg,
                        password});
            isvalidResult = ((bool)(results[0]));
            isvalidResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isvalidAsync(string fname, string lname, string reg, string password) {
            this.isvalidAsync(fname, lname, reg, password, null);
        }
        
        /// <remarks/>
        public void isvalidAsync(string fname, string lname, string reg, string password, object userState) {
            if ((this.isvalidOperationCompleted == null)) {
                this.isvalidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisvalidOperationCompleted);
            }
            this.InvokeAsync("isvalid", new object[] {
                        fname,
                        lname,
                        reg,
                        password}, this.isvalidOperationCompleted, userState);
        }
        
        private void OnisvalidOperationCompleted(object arg) {
            if ((this.isvalidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isvalidCompleted(this, new isvalidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/forget_password", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void forget_password([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string q, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ans, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string newp, out bool forget_passwordResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool forget_passwordResultSpecified) {
            object[] results = this.Invoke("forget_password", new object[] {
                        q,
                        ans,
                        newp});
            forget_passwordResult = ((bool)(results[0]));
            forget_passwordResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void forget_passwordAsync(string q, string ans, string newp) {
            this.forget_passwordAsync(q, ans, newp, null);
        }
        
        /// <remarks/>
        public void forget_passwordAsync(string q, string ans, string newp, object userState) {
            if ((this.forget_passwordOperationCompleted == null)) {
                this.forget_passwordOperationCompleted = new System.Threading.SendOrPostCallback(this.Onforget_passwordOperationCompleted);
            }
            this.InvokeAsync("forget_password", new object[] {
                        q,
                        ans,
                        newp}, this.forget_passwordOperationCompleted, userState);
        }
        
        private void Onforget_passwordOperationCompleted(object arg) {
            if ((this.forget_passwordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.forget_passwordCompleted(this, new forget_passwordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Adminisvalid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Adminisvalid([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string u, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string p, out bool AdminisvalidResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AdminisvalidResultSpecified) {
            object[] results = this.Invoke("Adminisvalid", new object[] {
                        u,
                        p});
            AdminisvalidResult = ((bool)(results[0]));
            AdminisvalidResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void AdminisvalidAsync(string u, string p) {
            this.AdminisvalidAsync(u, p, null);
        }
        
        /// <remarks/>
        public void AdminisvalidAsync(string u, string p, object userState) {
            if ((this.AdminisvalidOperationCompleted == null)) {
                this.AdminisvalidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdminisvalidOperationCompleted);
            }
            this.InvokeAsync("Adminisvalid", new object[] {
                        u,
                        p}, this.AdminisvalidOperationCompleted, userState);
        }
        
        private void OnAdminisvalidOperationCompleted(object arg) {
            if ((this.AdminisvalidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdminisvalidCompleted(this, new AdminisvalidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Addfood", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Addfood([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string n, int p, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string day, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string date, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string t) {
            this.Invoke("Addfood", new object[] {
                        n,
                        p,
                        pSpecified,
                        day,
                        date,
                        t});
        }
        
        /// <remarks/>
        public void AddfoodAsync(string n, int p, bool pSpecified, string day, string date, string t) {
            this.AddfoodAsync(n, p, pSpecified, day, date, t, null);
        }
        
        /// <remarks/>
        public void AddfoodAsync(string n, int p, bool pSpecified, string day, string date, string t, object userState) {
            if ((this.AddfoodOperationCompleted == null)) {
                this.AddfoodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddfoodOperationCompleted);
            }
            this.InvokeAsync("Addfood", new object[] {
                        n,
                        p,
                        pSpecified,
                        day,
                        date,
                        t}, this.AddfoodOperationCompleted, userState);
        }
        
        private void OnAddfoodOperationCompleted(object arg) {
            if ((this.AddfoodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddfoodCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Update_food", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update_food([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string n, int p, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string day, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string date) {
            this.Invoke("Update_food", new object[] {
                        n,
                        p,
                        pSpecified,
                        day,
                        date});
        }
        
        /// <remarks/>
        public void Update_foodAsync(string n, int p, bool pSpecified, string day, string date) {
            this.Update_foodAsync(n, p, pSpecified, day, date, null);
        }
        
        /// <remarks/>
        public void Update_foodAsync(string n, int p, bool pSpecified, string day, string date, object userState) {
            if ((this.Update_foodOperationCompleted == null)) {
                this.Update_foodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_foodOperationCompleted);
            }
            this.InvokeAsync("Update_food", new object[] {
                        n,
                        p,
                        pSpecified,
                        day,
                        date}, this.Update_foodOperationCompleted, userState);
        }
        
        private void OnUpdate_foodOperationCompleted(object arg) {
            if ((this.Update_foodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_foodCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ViewMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/mess_system")]
        public Food[] ViewMenu() {
            object[] results = this.Invoke("ViewMenu", new object[0]);
            return ((Food[])(results[0]));
        }
        
        /// <remarks/>
        public void ViewMenuAsync() {
            this.ViewMenuAsync(null);
        }
        
        /// <remarks/>
        public void ViewMenuAsync(object userState) {
            if ((this.ViewMenuOperationCompleted == null)) {
                this.ViewMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewMenuOperationCompleted);
            }
            this.InvokeAsync("ViewMenu", new object[0], this.ViewMenuOperationCompleted, userState);
        }
        
        private void OnViewMenuOperationCompleted(object arg) {
            if ((this.ViewMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewMenuCompleted(this, new ViewMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string r) {
            this.Invoke("UpdateStatus", new object[] {
                        r});
        }
        
        /// <remarks/>
        public void UpdateStatusAsync(string r) {
            this.UpdateStatusAsync(r, null);
        }
        
        /// <remarks/>
        public void UpdateStatusAsync(string r, object userState) {
            if ((this.UpdateStatusOperationCompleted == null)) {
                this.UpdateStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateStatus", new object[] {
                        r}, this.UpdateStatusOperationCompleted, userState);
        }
        
        private void OnUpdateStatusOperationCompleted(object arg) {
            if ((this.UpdateStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/submit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void submit() {
            this.Invoke("submit", new object[0]);
        }
        
        /// <remarks/>
        public void submitAsync() {
            this.submitAsync(null);
        }
        
        /// <remarks/>
        public void submitAsync(object userState) {
            if ((this.submitOperationCompleted == null)) {
                this.submitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitOperationCompleted);
            }
            this.InvokeAsync("submit", new object[0], this.submitOperationCompleted, userState);
        }
        
        private void OnsubmitOperationCompleted(object arg) {
            if ((this.submitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/checkbillbydate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void checkbillbydate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string date, out int checkbillbydateResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool checkbillbydateResultSpecified) {
            object[] results = this.Invoke("checkbillbydate", new object[] {
                        date});
            checkbillbydateResult = ((int)(results[0]));
            checkbillbydateResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void checkbillbydateAsync(string date) {
            this.checkbillbydateAsync(date, null);
        }
        
        /// <remarks/>
        public void checkbillbydateAsync(string date, object userState) {
            if ((this.checkbillbydateOperationCompleted == null)) {
                this.checkbillbydateOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckbillbydateOperationCompleted);
            }
            this.InvokeAsync("checkbillbydate", new object[] {
                        date}, this.checkbillbydateOperationCompleted, userState);
        }
        
        private void OncheckbillbydateOperationCompleted(object arg) {
            if ((this.checkbillbydateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkbillbydateCompleted(this, new checkbillbydateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/claculate_bill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void claculate_bill(out int claculate_billResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool claculate_billResultSpecified) {
            object[] results = this.Invoke("claculate_bill", new object[0]);
            claculate_billResult = ((int)(results[0]));
            claculate_billResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void claculate_billAsync() {
            this.claculate_billAsync(null);
        }
        
        /// <remarks/>
        public void claculate_billAsync(object userState) {
            if ((this.claculate_billOperationCompleted == null)) {
                this.claculate_billOperationCompleted = new System.Threading.SendOrPostCallback(this.Onclaculate_billOperationCompleted);
            }
            this.InvokeAsync("claculate_bill", new object[0], this.claculate_billOperationCompleted, userState);
        }
        
        private void Onclaculate_billOperationCompleted(object arg) {
            if ((this.claculate_billCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.claculate_billCompleted(this, new claculate_billCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/check", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void check([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reg, out int checkResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool checkResultSpecified) {
            object[] results = this.Invoke("check", new object[] {
                        reg});
            checkResult = ((int)(results[0]));
            checkResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void checkAsync(string reg) {
            this.checkAsync(reg, null);
        }
        
        /// <remarks/>
        public void checkAsync(string reg, object userState) {
            if ((this.checkOperationCompleted == null)) {
                this.checkOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckOperationCompleted);
            }
            this.InvokeAsync("check", new object[] {
                        reg}, this.checkOperationCompleted, userState);
        }
        
        private void OncheckOperationCompleted(object arg) {
            if ((this.checkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkCompleted(this, new checkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/check_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string check_status([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reg) {
            object[] results = this.Invoke("check_status", new object[] {
                        reg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void check_statusAsync(string reg) {
            this.check_statusAsync(reg, null);
        }
        
        /// <remarks/>
        public void check_statusAsync(string reg, object userState) {
            if ((this.check_statusOperationCompleted == null)) {
                this.check_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncheck_statusOperationCompleted);
            }
            this.InvokeAsync("check_status", new object[] {
                        reg}, this.check_statusOperationCompleted, userState);
        }
        
        private void Oncheck_statusOperationCompleted(object arg) {
            if ((this.check_statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.check_statusCompleted(this, new check_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Addfine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Addfine() {
            this.Invoke("Addfine", new object[0]);
        }
        
        /// <remarks/>
        public void AddfineAsync() {
            this.AddfineAsync(null);
        }
        
        /// <remarks/>
        public void AddfineAsync(object userState) {
            if ((this.AddfineOperationCompleted == null)) {
                this.AddfineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddfineOperationCompleted);
            }
            this.InvokeAsync("Addfine", new object[0], this.AddfineOperationCompleted, userState);
        }
        
        private void OnAddfineOperationCompleted(object arg) {
            if ((this.AddfineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddfineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/mess_system")]
    public partial class Food {
        
        private string dateField;
        
        private string dayField;
        
        private string nameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/mess_system")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void registerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void isvalidCompletedEventHandler(object sender, isvalidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isvalidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isvalidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isvalidResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isvalidResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void forget_passwordCompletedEventHandler(object sender, forget_passwordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class forget_passwordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal forget_passwordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool forget_passwordResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool forget_passwordResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AdminisvalidCompletedEventHandler(object sender, AdminisvalidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdminisvalidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdminisvalidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool AdminisvalidResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool AdminisvalidResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddfoodCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Update_foodCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ViewMenuCompletedEventHandler(object sender, ViewMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViewMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Food[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Food[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void submitCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void checkbillbydateCompletedEventHandler(object sender, checkbillbydateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkbillbydateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkbillbydateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int checkbillbydateResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool checkbillbydateResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void claculate_billCompletedEventHandler(object sender, claculate_billCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class claculate_billCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal claculate_billCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int claculate_billResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool claculate_billResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void checkCompletedEventHandler(object sender, checkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int checkResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool checkResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void check_statusCompletedEventHandler(object sender, check_statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class check_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal check_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddfineCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591